server:
  port: 3003
spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      routes:
      - id: CitizenServer
        uri: http://localhost:3001/
        predicates:
        - Path=/citizen/**
      - id: VaccinationServer
        uri: http://localhost:3002/
        predicates:
        - Path=/vaccinationcenter/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true